---
title: "Instacart Interactive Dashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(flexdashboard)
library(plotly)
library(tidyverse)
library(p8105.datasets)
```

```{r}
# Load the Instacart dataset
data("instacart")
```

```{r}
# Data Cleaning Step
instacart_c = instacart |>
  filter(!is.na(order_dow) & !is.na(order_hour_of_day)) |>  
  mutate(
    order_dow = factor(order_dow, labels = c("Sun", "Mon", "Tue", "Wed", "Thu", "Fri", "Sat")),
    reordered = factor(reordered, levels = c(0, 1), labels = c("No", "Yes"))
  )

# Take a sample of the data for better performance
set.seed(123)
instacart_s <- instacart_c |>
  sample_n(8000)  
```


Column {data-width=650}
-----------------------------------------------------------------------
### Overview of Orders by Department

```{r}
instacart_s |>
  group_by(department) |>
  summarise(count = n()) |>
  arrange(desc(count)) |>
  plot_ly(
    x = ~department,
    y = ~count,
    type = 'bar',
      color = ~department,
      colors = "viridis" ) |>
  layout(
    title = "Number of Products Ordered by Department",
    xaxis = list(title = "Department", tickangle = 45),
    yaxis = list(title = "Number of Orders") )

```

Column {data-width=350}
-----------------------------------------------------------------------

### Order Number vs Add to Cart Order

```{r}
instacart_s |>
  plot_ly(
    x = ~order_number,
    y = ~add_to_cart_order,
    type = 'scatter',
    mode = 'markers',
    color = ~order_dow,
    colors = "plasma",
    marker = list(size = 6, opacity = 0.6)
  ) |>
  layout(
    title = "Order Number vs Add to Cart Order",
    xaxis = list(title = "Order Number"),
    yaxis = list(title = "Add to Cart Order")
  )
```

### Add to Cart Order by Day of the Week

```{r}
instacart_s |>
  plot_ly(
    x = ~order_dow,
    y = ~add_to_cart_order,
    type = 'box',
    color = ~order_dow,
    colors = "viridis"
  ) |>
  layout(
    title = "Add to Cart Order by Day of the Week",
    xaxis = list(title = "Day of the Week", tickangle = 0),
    yaxis = list(title = "Add to Cart Order")
  )
```



